// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBql9zY3iAqlmrZM1WPYZW63ghY2Vit484',
    appId: '1:1018725801235:web:6f32eec4b27de4af3fcee6',
    messagingSenderId: '1018725801235',
    projectId: 'cinemax-e22bb',
    authDomain: 'cinemax-e22bb.firebaseapp.com',
    storageBucket: 'cinemax-e22bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7CZmfgNF30Bk_4uLYl0YWkEYzwK3JZHU',
    appId: '1:1018725801235:android:92ed3c51ce11ab6a3fcee6',
    messagingSenderId: '1018725801235',
    projectId: 'cinemax-e22bb',
    storageBucket: 'cinemax-e22bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-u1B6smyXlLFMU7RN9X3pnMfkyMpBQ0s',
    appId: '1:1018725801235:ios:14a4c71eefecfc173fcee6',
    messagingSenderId: '1018725801235',
    projectId: 'cinemax-e22bb',
    storageBucket: 'cinemax-e22bb.firebasestorage.app',
    iosBundleId: 'com.example.gedeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-u1B6smyXlLFMU7RN9X3pnMfkyMpBQ0s',
    appId: '1:1018725801235:ios:14a4c71eefecfc173fcee6',
    messagingSenderId: '1018725801235',
    projectId: 'cinemax-e22bb',
    storageBucket: 'cinemax-e22bb.firebasestorage.app',
    iosBundleId: 'com.example.gedeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBql9zY3iAqlmrZM1WPYZW63ghY2Vit484',
    appId: '1:1018725801235:web:b48bb14a50d50ffc3fcee6',
    messagingSenderId: '1018725801235',
    projectId: 'cinemax-e22bb',
    authDomain: 'cinemax-e22bb.firebaseapp.com',
    storageBucket: 'cinemax-e22bb.firebasestorage.app',
  );
}
